- name: Deploy node_exporter
  hosts: all
  roles:
    - cloudalchemy.node-exporter
  tags:
    - node_exporter

- name: Deploy slurm_exporter
  hosts: slurm_exporter
  vars:
    slurm_exporter_web_listen_address: 0.0.0.0:1234
  roles:
    - stackhpc.ansible_slurm_exporter
  tags:
    - slurm_exporter

- name: Deploy sockpuppet
  hosts: sockpuppet
  vars:
    sockpuppet_listen_address: 0.0.0.0
    sockpuppet_listen_port: 30000
    sockpuppet_config_template: templates/sockpuppet_config.py
  roles:
    - stackhpc.sockpuppet
  tags:
    - sockpuppet

- name: Setup core monitoring software
  hosts: prometheus
  roles:
    - cloudalchemy.blackbox-exporter
    - cloudalchemy.snmp-exporter
    - cloudalchemy.prometheus
    - cloudalchemy.alertmanager
  tags:
    - prometheus

- name: Deploy grafana
  hosts: grafana
  roles:
    - cloudalchemy.grafana
  tags:
    - grafana
